### ISSUE TITLE
Showcase Composed Task capabilities

### ISSUE THREAD

**Issue by sabbyanandan** [spring-io/dataflow.spring.io#180]
As a developer, I'd like to showcase the Composed Task capabilities starting from a simplistic to advanced use-cases on the supported platforms.

Topics to consider:
- [x] Security (@cppwfs -WIP) - simple user/pass and oauth configurations (for: local and cf)
- [x] Task: (@markpollack/@cppwfs  - WIP) Passing args, deployer props, and the differences with examples (for: ctr and the child tasks)
- [x] Schedules(@cppwfs - WIP): Passing args, deployer props, and the differences with examples (for: ctr and the child tasks)
- [x] Restarting a child task in a graph(@cppwfs - WIP) - what is supported and not
- [x] API access in SCDF to launch a composed task
- [x] Tracking exit codes at the level of the CT graph, and at the level of individual tasks
- [x] Use of `core-pool-size`, `max-pool-size` and `queue-capacity`, and the reasoning (@cppwfs -WIP)
- [x] Foundation Flows(@cppwfs -WIP)  and considerations i.e split/conditional execution/transitions

Some additional thoughts.

In the docs we always start with the DSL and then see the graph.  Authoring the composed task this way gets more complicated as the complexity of the graph increases.  There should be a chapter that shows how to build the graph using drag and drop, in particular for the case of transitional execution, where I think the fluency of the DSL is the weakest.
