### ISSUE TITLE
EPIC: Refresh Microsite to 3.x

### ISSUE THREAD

**Issue by cppwfs** [spring-io/dataflow.spring.io#526]
- [ ] Update Installation docs
- [ ] Update Stream docs
- [ ] Update Batch docs
- [ ] Update CTR docs
- [ ] Update Features
- [ ] Update Recipes
- [ ] Update Style
